version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - backend_network

  node_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: dpcode72/node_app:${TIMESTAMP}
    container_name: node_app
    ports:
      - "${PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: ${SERVER_PORT}
    volumes:
      - ./server:/usr/src/app
    restart: always
    networks:
      - backend_network
    env_file:
      - .env

  react_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: dpcode72/react_app:${TIMESTAMP}
    container_name: react_app
    ports:
      - "8000:80"
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    networks:
      - backend_network
    env_file:
      - .env

volumes:
  mysql_data:
    driver: local

networks:
  backend_network:
